# Generated by Django 5.0 on 2023-12-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmed_date', models.DateField()),
                ('payment_method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('name_client', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInvoices',
            fields=[
                ('expense_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
        migrations.CreateModel(
            name='TaxInvoices',
            fields=[
                ('tax_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('expense_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expenseinvoices')),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('shortage_quantity', models.IntegerField()),
                ('warning_message', models.CharField(max_length=255)),
                ('expense_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expenseinvoices')),
            ],
        ),
    ]
