# Generated by Django 5.0 on 2023-12-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_expenseinvoices_expenseinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.inventory'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
