# Generated by Django 5.0 on 2023-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_inventory_order_quantity_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
