# Generated by Django 5.0 on 2023-12-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inventory_entry_date_alter_inventory_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inventory',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.inventory'),
        ),
    ]
