# Generated by Django 5.0 on 2023-12-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_inventory_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.inventory'),
        ),
    ]
