# Generated by Django 5.0 on 2023-12-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_subtotal_alter_order_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inventory',
        ),
    ]
