# Generated by Django 5.0 on 2023-12-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_expenseinvoice_invoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warnings',
        ),
    ]
