# Generated by Django 5.0 on 2023-12-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenseinvoice',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='confirmed_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
